version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '[patch] - '
    allow:
      - dependency-type: 'production'
    open-pull-requests-limit: 0
