on: push
name: Install and Test
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@master
      with:
        args: ci
    - name: Test
      uses: actions/npm@master
      with:
        args: t
